version: "3"

services:
  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    command: "bin/spark-class org.apache.spark.deploy.master.Master"

  spark-worker:
    image: apache/spark:latest
    container_name: spark-worker
    hostname: spark-worker
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    command: "bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
