version: "3"

services:
  namenode:
    image: sequenceiq/hadoop-docker:new
    container_name: namenode
    expose:
      - "50070"
    ports:
      - "50070:50070"
    command: /etc/bootstrap.sh -d -namenode
    networks:
      - hadoop-net

  datanode:
    image: sequenceiq/hadoop-docker:new
    container_name: datanode
    expose:
      - "50075"
    ports:
      - "50075:50075"
    links:
      - namenode
    command: /etc/bootstrap.sh -d -datanode
    networks:
      - hadoop-net

  resourcemanager:
    image: sequenceiq/hadoop-docker:new
    container_name: resourcemanager
    expose:
      - "8088"
    ports:
      - "8088:8088"
    links:
      - namenode
    command: /etc/bootstrap.sh -d -resourcemanager
    networks:
      - hadoop-net

  nodemanager:
    image: sequenceiq/hadoop-docker:new
    container_name: nodemanager
    expose:
      - "8042"
    ports:
      - "8042:8042"
    links:
      - namenode
    command: /etc/bootstrap.sh -d -nodemanager
    networks:
      - hadoop-net

networks:
  hadoop-net:
    external: true
