apiVersion: apps/v1
kind: Deployment 
metadata:
  name: spark-master
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: spark-master-container
        image: spark-hadoop:3.2.0
        command: ["/spark-master"]
        ports:
        - name: spark
          containerPort: 7077
        - name: webui
          containerPort: 8080
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "4"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
        env:
          - name: SPARK_EXECUTOR_MEMORY
            value: "1g"
          - name: SPARK_DRIVER_MEMORY
            value: "512m"
          - name: SPARK_DRIVER_MAXRESULTSIZE
            value: "1g"
          - name: SPARK_KUBERNETES_EXECUTOR_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SPARK_LOCAL_DIRS
            value: "/tmp"
          - name: SPARK_WORKER_DIR
            value: "/tmp"
          - name: SPARK_HISTORY_OPTS
            value: "-Dspark.history.ui.port=4040"
          - name: SPARK_SUBMIT_OPTS
            value: "--conf spark.eventLog.enabled=true --conf spark.eventLog.dir=file:/tmp/spark-events"
          - name: SPARK_EXECUTOR_INSTANCES
            value: "2"
          - name: SPARK_EXECUTOR_CORES
            value: "2"
          - name: SPARK_DRIVER_BIND_ADDRESS
            value: "0.0.0.0"
          - name: SPARK_BLOCKMGR_PORT
            value: "7070"
          - name: SPARK_KUBE_EXECUTOR_IMAGE_PULL_POLICY
            value: "IfNotPresent"
          - name: SPARK_KUBE_DRIVER_IMAGE_PULL_POLICY
            value: "IfNotPresent"
          - name: SPARK_EXECUTOR_EXTRA_CLASSPATH
            value: "/path/to/your/libs"
          - name: SPARK_CONF_DIR
            value: "/path/to/your/spark-config"
          - name: SPARK_MASTER
            value: "k8s://https://kubernetes.default.svc:443"
